
CREATE TABLE `project` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL COMMENT '项目名称',
  `frequency` int(5) NOT NULL COMMENT '监测频率，单位秒',
  `deleted` TINYINT(1) DEFAULT 0 COMMENT '是否删除',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `device_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app_key` varchar(50) NOT NULL COMMENT 'app key',
  `secret` varchar(50) NOT NULL COMMENT 'secret',
  `access_token` varchar(100) DEFAULT '' COMMENT 'access_token',
  `expire_at` BIGINT DEFAULT 0 COMMENT '过期时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `device` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `device_serial` varchar(50) NOT NULL COMMENT '设备序列号',
  `channel_no` TINYINT(1) DEFAULT 1 COMMENT '通道号，IPC设备为1',
  `status` TINYINT(1) DEFAULT NULL COMMENT '设备状态',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `monitor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` int(5) NOT NULL COMMENT '项目编号',
  `meter_level` TINYINT(1) NOT NULL COMMENT '表级别',
  `name` varchar(100) NOT NULL COMMENT '监测点名称',
  `device_no` int(5) NOT NULL COMMENT '设备编号',
  `device_id` int(5) NOT NULL COMMENT '设备ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
